# Use the official MongoDB image
FROM mongo:latest

# No need for further configuration here unless you have specific requirements


sensorDB> db.sensordatas.find().pretty()
[
  {
    _id: ObjectId('6707f2dc9c5bdec2e662b3a8'),
    temperature: 25.2,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:32.905Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2de9c5bdec2e662b3aa'),
    temperature: 25,
    humidity: 45,
    timestamp: ISODate('2024-10-10T15:29:34.260Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2df9c5bdec2e662b3ac'),
    temperature: 25,
    humidity: 45,
    timestamp: ISODate('2024-10-10T15:29:35.696Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2e79c5bdec2e662b3ae'),
    temperature: 25,
    humidity: 47,
    timestamp: ISODate('2024-10-10T15:29:43.814Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2e99c5bdec2e662b3b0'),
    temperature: 25,
    humidity: 47,
    timestamp: ISODate('2024-10-10T15:29:45.763Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f99c5bdec2e662b3b2'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:30:01.387Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2ef9c5bdec2e662b3b4'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:51.420Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f09c5bdec2e662b3b6'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:52.674Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f29c5bdec2e662b3b8'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:54.233Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f39c5bdec2e662b3ba'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:55.630Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f3039c5bdec2e662b3bc'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:30:11.378Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f69c5bdec2e662b3be'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:58.365Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f79c5bdec2e662b3c0'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:29:59.796Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2f99c5bdec2e662b3c2'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:30:01.236Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2fa9c5bdec2e662b3c4'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:30:02.628Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2fc9c5bdec2e662b3c6'),
    temperature: 24.9,
    humidity: 47,
    timestamp: ISODate('2024-10-10T15:30:04.066Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f2fd9c5bdec2e662b3c8'),
    temperature: 24.9,
    humidity: 47,
    timestamp: ISODate('2024-10-10T15:30:05.858Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f30d9c5bdec2e662b3ca'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:30:21.455Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f3009c5bdec2e662b3cc'),
    temperature: 24.9,
    humidity: 46,
    timestamp: ISODate('2024-10-10T15:30:08.401Z'),
    __v: 0
  },
  {
    _id: ObjectId('6707f3019c5bdec2e662b3ce'),
    temperature: 25,
    humidity: 53,
    timestamp: ISODate('2024-10-10T15:30:09.938Z'),
    __v: 0
  }
]
Type "it" for more